name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Check Node version
        run: node -v
        
      - name: Install packages
        run: yarn install

      - name: Build
        run: yarn build
        
      - name: Create zip
        run: zip -qq -r build.zip appspec.yml scripts/ dist/
        shell: bash
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_ACCESS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Upload to S3
        run:
          aws s3 cp --region ${{ secrets.AWS_REGION }} ./build.zip s3://yahma25-playground-deploy/

      # CodeDeploy 애플리케이션
      - name: Deploy to EC2
        run:
          aws deploy create-deployment
            --application-name playground
            --deployment-config-name CodeDeployDefault.AllAtOnce
            --deployment-group-name deploy-playground
            --s3-location bucket=yahma25-playground-deploy,key=build.zip,bundleType=zip
